// This file was auto-generated by prisma-generator-typescript-interfaces

import { Prisma } from "@prisma/client";
import { SenderAccountState } from "../models/enums";

export type UserRole = "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";

export type CampaignStatus = "DRAFT" | "SCHEDULED" | "ACTIVE" | "PAUSED" | "STOPPED" | "COMPLETED" | "ARCHIVED";

export type LeadStatus = "PENDING" | "QUEUED" | "SENT" | "OPENED" | "CLICKED" | "REPLIED" | "BOUNCED" | "UNSUBSCRIBED" | "FAILED";

export type EmailSendStatus = "QUEUED" | "SENDING" | "SENT" | "FAILED" | "BOUNCED" | "REPLIED" | "OPENED" | "CLICKED" | "STOPPED";

export type SequenceType = "EMAIL" | "WAIT" | "MANUAL_TASK";

export type EmailProvider = "smtp" | "gmail" | "outlook" | "imap";

export type WarmupStatus = "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "PAUSED";

export type PlanCode = "FREE" | "STARTER" | "PROFESSIONAL" | "ENTERPRISE";

export type BillingPeriod = "MONTHLY" | "YEARLY";

export type EventType = "SENT" | "DELIVERED" | "OPENED" | "CLICKED" | "REPLIED" | "BOUNCED" | "UNSUBSCRIBED" | "COMPLAINED";

export type StopSending = "CLICK" | "OPEN" | "REPLY";


export interface AuthRequest extends Request {
  user: { id: string; orgId: string };
}

export interface Organization {
  id: string;
  name: string;
  domain: string | null;
  phone: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  zip: string | null;
  industry: string | null;
  description: string | null;
  logoUrl: string | null;
  timezone: string;
  createdAt: Date;
  updatedAt: Date;
  users?: User[];
  senderAccounts?: SenderAccount[];
  campaigns?: Campaign[];
  leads?: Lead[];
  plans?: OrganizationPlan[];
  apiKeys?: ApiKey[];
}

export interface User {
  id: string;
  email: string;
  fullName: string;
  password: string;
  phone: string | null;
  role: UserRole;
  profilePicture: string | null;
  isVerified: boolean;
  isActive: boolean;
  lastLoginAt: Date | null;
  timezone: string | null;
  otpCode: string | null;
  otpExpiresAt: Date | null;
  resetToken: string | null;
  resetTokenExpiresAt: Date | null;
  activationToken: string | null;
  activationTokenExpiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  orgId: string;
  organization?: Organization;
  leadsUploaded?: Lead[];
  campaigns?: Campaign[];
}

export interface AccessToken {
  id: string;
  token: string;
  userId: string;
  expiresAt: Date;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ApiKey {
  id: string;
  name: string;
  key: string;
  lastUsedAt: Date | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  orgId: string;
  organization?: Organization;
}

export interface SenderAccount {
  id: string;
  accountId: string;
  state: SenderAccountState;

  email: string;
  name: string | null;
  provider: EmailProvider;
  replyTo?: string | null;

  errorReason?: string;
  errorDetails?: Record<string, unknown>;
  erroredAt?: Date;

  smtpHost: string | null;
  smtpPort: number | null;
  smtpUser: string | null;
  smtpPass: string | null;
  smtpSecure: boolean | null;

  imapHost: string | null;
  imapPort: number | null;
  imapUser: string | null;
  imapPass: string | null;
  imapSecure: boolean | null;
  
  accessToken: string | null;
  refreshToken: string | null;
  tokenExpiry: Date | null;
  dailyLimit: number;
  hourlyLimit: number;
  minDelaySeconds: number;
  isEnabled: boolean;
  isVerified: boolean;
  warmupStatus: WarmupStatus;
  warmupStartedAt: Date | null;
  warmupDailyIncrement: number;
  signature: string | null;
  createdAt: Date;
  updatedAt: Date;
  orgId: string;
  organization?: Organization;
  runtime?: SenderRuntime[];
  emailSends?: EmailSend[];
  campaignSenders?: CampaignSender[];
}

export type CreateSenderAccount = {
  accountId: string
  email: string
  name?: string | null
  provider: EmailProvider

  // SMTP Config
  smtpHost?: string | null
  smtpPort?: number | null
  smtpUser?: string | null
  smtpPass?: string | null
  smtpSecure?: boolean | null
  
  // IMAP Config
  imapHost?: string | null
  imapPort?: number | null
  imapUser?: string | null
  imapPass?: string | null
  imapSecure?: boolean | null

  // OAuth Config (for Gmail/Outlook API)
  accessToken?: string | null
  refreshToken?: string | null
  tokenExpiry?: Date | string | null

  dailyLimit?: number
  hourlyLimit?: number
  minDelaySeconds?: number
  isEnabled?: boolean
  isVerified?: boolean

  // Warmup
  warmupStatus?: WarmupStatus
  warmupStartedAt?: Date | string | null
  warmupDailyIncrement?: number
  
  signature?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutUsersNestedInput;
  runtime?: Prisma.SenderRuntimeUpdateManyWithoutSenderNestedInput
  emailSends?: Prisma.EmailSendUpdateManyWithoutSenderNestedInput
  campaignSenders?: Prisma.CampaignSenderUpdateManyWithoutSenderNestedInput
}

export interface UpdateSenderAccount {
  email?: string
  name?: string | null
  replyTo?: string | ""
  provider?: EmailProvider
  smtpHost?: string | null
  smtpPort?: number | null
  smtpUser?: string | null
  smtpPass?: string | null
  smtpSecure?: boolean | null
  imapHost?: string | null
  imapPort?: number | null
  imapUser?: string | null
  imapPass?: string | null
  imapSecure?: boolean | null
  accessToken?: string | null
  refreshToken?: string | null
  tokenExpiry?: Date | string | null
  dailyLimit?: number
  hourlyLimit?: number
  minDelaySeconds?: number
  isEnabled?: boolean
  isVerified?: boolean
  warmupStatus?: WarmupStatus
  warmupStartedAt?: Date | string | null
  warmupDailyIncrement?: number
  signature?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutUsersNestedInput;
  runtime?: Prisma.SenderRuntimeUpdateManyWithoutSenderNestedInput
  emailSends?: Prisma.EmailSendUpdateManyWithoutSenderNestedInput
  campaignSenders?: Prisma.CampaignSenderUpdateManyWithoutSenderNestedInput
}
export interface SenderRuntime {
  id: string;
  senderId: string;
  dayKey: string;
  sentToday: number;
  sentThisHour: number;
  hourKey: string | null;
  lastSentAt: Date | null;
  lockedAt: Date | null;
  lockedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
  sender?: SenderAccount;
}

export interface Campaign {
  id: string;
  name: string;
  description: string | null;
  status: CampaignStatus;
  timezone: string;
  sendDays: string[];
  windowStart: string;
  windowEnd: string;
  intervalMinutes: number;
  maxEmailsPerDay: number;
  sendAsPlainText: boolean;
  trackOpens: boolean;
  trackClicks: boolean;
  stopSending: StopSending;
  sendingPriority: number;
  autoPauseSameDomain: boolean;
  bounceRateThreshold: number;
  autoPauseOnHighBounce: boolean;
  includeUnsubscribeLink: boolean;
  unsubscribeText: string | null;
  createdAt: Date;
  updatedAt: Date;
  scheduledAt: Date | null;
  startedAt: Date | null;
  completedAt: Date | null;
  orgId: string;
  organization?: Organization;
  createdById: string | null;
  createdBy?: User | null;
  sequences?: Sequence[];
  leads?: CampaignLead[];
  senders?: CampaignSender[];
  runtime?: CampaignRuntime | null;
  analytics?: CampaignAnalytics | null;
  emailSends?: EmailSend[];
}

export interface CampaignSender {
  id: string;
  campaignId: string;
  senderId: string;
  weight: number;
  isActive: boolean;
  createdAt: Date;
  campaign?: Campaign;
  sender?: SenderAccount;
}

export interface CampaignRuntime {
  id: string;
  campaignId: string;
  dayKey: string;
  sentToday: number;
  nextRunAt: Date;
  lockedAt: Date | null;
  lockedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
  campaign?: Campaign;
}

export interface CampaignAnalytics {
  id: string;
  campaignId: string;
  totalLeads: number;
  sentCount: number;
  deliveredCount: number;
  openedCount: number;
  clickedCount: number;
  repliedCount: number;
  bouncedCount: number;
  unsubscribedCount: number;
  failedCount: number;
  openRate: number;
  clickRate: number;
  replyRate: number;
  bounceRate: number;
  createdAt: Date;
  updatedAt: Date;
  campaign?: Campaign;
}

export interface Sequence {
  id: string;
  campaignId: string;
  seqNumber: number;
  type: SequenceType;
  delayDays: number;
  delayHours: number;
  delayMinutes: number;
  subject: string | null;
  bodyHtml: string | null;
  bodyText: string | null;
  taskTitle: string | null;
  taskDescription: string | null;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  campaign?: Campaign;
  emailSends?: EmailSend[];
}

export interface Lead {
  id: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  company: string | null;
  designation: string | null;
  industry: string | null;
  linkedinUrl: string | null;
  website: string | null;
  phone: string | null;
  city: string | null;
  state: string | null;
  country: string | null;
  customFields: JsonValue | null;
  isVerified: boolean;
  isBlocked: boolean;
  isUnsubscribed: boolean;
  unsubscribedAt: Date | null;
  source: string | null;
  fileName: string | null;
  createdAt: Date;
  updatedAt: Date;
  orgId: string;
  organization?: Organization;
  uploadedById: string | null;
  uploadedBy?: User | null;
  campaigns?: CampaignLead[];
  emailSends?: EmailSend[];
  events?: EmailEvent[];
}

export interface CampaignLead {
  id: string;
  campaignId: string;
  leadId: string;
  status: LeadStatus;
  currentSequenceStep: number;
  nextSendAt: Date | null;
  isStopped: boolean;
  stoppedAt: Date | null;
  stoppedReason: string | null;
  lastSentAt: Date | null;
  lastOpenedAt: Date | null;
  lastClickedAt: Date | null;
  lastRepliedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  campaign?: Campaign;
  lead?: Lead;
}

export interface EmailSend {
  id: string;
  status: EmailSendStatus;
  sequenceStep: number | null;
  providerMsgId: string | null;
  threadId: string | null;
  errorMessage: string | null;
  errorCode: string | null;
  attempts: number;
  lastAttemptAt: Date | null;
  queuedAt: Date;
  sentAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  campaignId: string;
  campaign?: Campaign;
  senderId: string;
  sender?: SenderAccount;
  leadId: string;
  lead?: Lead;
  sequenceId: string | null;
  sequence?: Sequence | null;
  events?: EmailEvent[];
}

export interface EmailEvent {
  id: string;
  type: EventType;
  timestamp: Date;
  ipAddress: string | null;
  userAgent: string | null;
  linkUrl: string | null;
  city: string | null;
  country: string | null;
  createdAt: Date;
  emailSendId: string;
  emailSend?: EmailSend;
  leadId: string;
  lead?: Lead;
}

export interface Plan {
  id: number;
  code: PlanCode;
  name: string;
  description: string | null;
  priceMonthly: Decimal | null;
  priceYearly: Decimal | null;
  isContactSales: boolean;
  maxUsers: number | null;
  maxSenderAccounts: number | null;
  maxLeadsPerMonth: number | null;
  maxEmailsPerMonth: number | null;
  maxCampaigns: number | null;
  hasEmailVerification: boolean;
  hasEmailWarmup: boolean;
  hasUnifiedInbox: boolean;
  hasApiAccess: boolean;
  hasCustomDomain: boolean;
  hasAdvancedAnalytics: boolean;
  hasPrioritySupport: boolean;
  createdAt: Date;
  updatedAt: Date;
  subscriptions?: OrganizationPlan[];
}

export interface OrganizationPlan {
  id: number;
  orgId: string;
  planId: number;
  billingPeriod: BillingPeriod;
  isActive: boolean;
  startsAt: Date;
  endsAt: Date | null;
  emailsSentThisPeriod: number;
  leadsAddedThisPeriod: number;
  senderAccountsCount: number;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string | null;
  createdAt: Date;
  updatedAt: Date;
  organization?: Organization;
  plan?: Plan;
}

type JsonValue = string | number | boolean | { [key in string]?: JsonValue } | Array<JsonValue> | null;

type Decimal = { valueOf(): string };

export interface EmailAccount {
  type: "gmail" | "outlook" | "imap";
  email: string;
  account_id: string;
  oauth2: {
    clientId?: string;
    clientSecret?: string;
    tokens: {
      access_token?: string;
      refresh_token?: string;
      expiry_date?: number;
      expires_in?: number;
    };
  };
  smtp?: {
    host: string;
    port: number;
    secure: boolean;
    auth: {
      user: string;
      pass: string;
    };
  };
}

// Campaign Sender with Stats
export interface CampaignSenderStats {
  sent: number;
  queued: number;
  failed: number;
  total: number;
  uniqueLeads: number; // Number of unique leads contacted by this sender
}

export interface CampaignSenderWithStats {
  id: string;
  senderId: string;
  accountId: string;
  email: string;
  name: string | null;
  provider: string;
  dailyLimit: number;
  isEnabled: boolean;
  isActive: boolean;
  weight: number;
  stats: CampaignSenderStats;
}
